Update dataset-curation.md
neuropoly/intranet.neuro.polymtl.ca pull request #111
Opened 2024-01-12 20:49 UTC by NathanMolinier

## Description

This PR will be used to update the last changes of our data curation convention

2024-01-12 21:27 UTC, jcohenadad commented on data/dataset-curation.md
> +                    ├── sub-001_acq-sag_T2w_label-discs_dlabel.nii.gz  # discrete discs labeling
```suggestion
                    ├── sub-001_acq-sag_T2w_label-discs_dlabel.nii.gz  # discrete discs labeling using the following convention: https://spinalcordtoolbox.com/user_section/tutorials/vertebral-labeling/labeling-conventions.html
```

2024-01-15 18:36 UTC, jcohenadad requested changes
Great start! thank you @NathanMolinier. This could be added as well: https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/108#issuecomment-1892628394

2024-01-15 19:18 UTC, NathanMolinier commented
> Great start! thank you @NathanMolinier. This could be added as well: [#108 (comment)](https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/108#issuecomment-1892628394)

Is it good like that ? [3042c39](https://github.com/neuropoly/intranet.neuro.polymtl.ca/pull/111/commits/3042c39ddb49407b3cb33a179f7865bf8bc02474)

2024-01-16 21:24 UTC, jcohenadad approved these changes
Amazing work ❤️

2024-01-16 21:26 UTC, merged