remove document not included in any toctree
neuropoly/intranet.neuro.polymtl.ca pull request #55
Opened 2022-06-20 23:29 UTC by RignonNoel

fix #7 

As proposed by @kousu I ran sphinx locally and I checked the warnings about toctree. It gives me all the dead pages and I deleted them.

I did some search for every files, it seems correct and it seems to work well in local.

2022-07-21 03:50 UTC, kousu commented
To measure this, I first estimated the baseline noise level:

```
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

<details><summary>_build1</summary>

```
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ make html
Running Sphinx v4.2.0
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=[], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=4, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 113 source files that are out of date
updating environment: [new config] 113 added, 0 changed, 0 removed
reading sources... [100%] writing-articles                                                                                                            
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/computing-resources/neuropoly/gpus.md:1038: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/computing-resources/printer.md:10: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:10: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:14: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:28: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:32: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/README.md:22: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:15: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:75: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:83: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:90: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/image-processing-software/diffusion-simulator.md:17: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/image-processing-software/itk-snap.md:5: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:20: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:28: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:36: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:42: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:52: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:60: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:78: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:108: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:120: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:377: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:395: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:504: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:514: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:535: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:555: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:571: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:579: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:666: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:730: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:734: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/microsoft-word.md:3: WARNING: Non-consecutive header level increase; H1 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/microsoft-word.md:10: WARNING: Non-consecutive header level increase; H1 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/vagrant.md:7: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/vagrant.md:12: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/virtualbox.md:3: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/virtualbox.md:13: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GR [...]

2022-07-21 03:51 UTC, kousu commented
Next I did the build on this branch:

<details><summary>_build-cleaner</summary>

```
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ git checkout nr/clean-up-warnings 
Switched to branch 'nr/clean-up-warnings'
Your branch and 'origin/nr/clean-up-warnings' have diverged,
and have 18 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ git rebase master
Current branch nr/clean-up-warnings is up to date.
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ make html
Running Sphinx v4.2.0
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=[], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=4, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 99 source files that are out of date
updating environment: [new config] 99 added, 0 changed, 0 removed
reading sources... [100%] writing-articles                                                                                                            
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/computing-resources/neuropoly/gpus.md:1038: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/computing-resources/printer.md:10: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:10: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:14: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:28: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/courses.md:32: WARNING: Disallowed nested header found, converting to rubric [myst.nested_header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/README.md:22: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:15: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:75: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:83: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/deep-learning/tensorflow.md:90: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/image-processing-software/diffusion-simulator.md:17: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/image-processing-software/itk-snap.md:5: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:20: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:28: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:36: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:42: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:52: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:60: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:78: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:108: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/docker/README.md:120: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:377: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:395: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:504: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:514: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:535: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:555: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:571: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:579: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:666: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:730: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.md:734: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/microsoft-word.md:3: WARNING: Non-consecutive header level increase; H1 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/microsoft-word.md:10: WARNING: Non-consecutive header level increase; H1 to H4 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/vagrant.md:7: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/vagrant.md:12: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/geek-tips/misc/virtual-machines/virtualbox.md:3: WARNING: Non-conse [...]

2022-07-21 03:53 UTC, kousu commented
And diff'd again:

<details>

```diff
p115628@joplin:~/src/intranet.neuro.polymtl.ca$ diff -ru _build1 _build-cleaner/
Only in _build1/doctrees: computer-setup.doctree
Only in _build1/doctrees: dropbox-google-drive.doctree
Binary files _build1/doctrees/environment.pickle and _build-cleaner/doctrees/environment.pickle differ
Only in _build1/doctrees: learning-and-resources
Only in _build1/doctrees: purchasing-hardware-and-lab-supplies.doctree
Only in _build1/doctrees/rf-lab/3d-printing: octoprint.doctree
Only in _build1/doctrees: tips-and-tricks
Only in _build-cleaner/html: _build1
Only in _build-cleaner/html: _build2
Only in _build1/html: computer-setup.html
diff -ru _build1/html/computing-resources/data/duke.html _build-cleaner/html/computing-resources/data/duke.html
--- _build1/html/computing-resources/data/duke.html	2022-07-20 21:30:28.560188668 -0400
+++ _build-cleaner/html/computing-resources/data/duke.html	2022-07-20 23:41:45.476556841 -0400
@@ -990,8 +990,8 @@
 <h2>Mount with GUI<a class="headerlink" href="#mount-with-gui" title="Permalink to this headline">#</a></h2>
 <p>When working on campus or <span class="xref myst">over the VPN</span>, you can connect your computer to <code class="docutils literal notranslate"><span class="pre">duke</span></code>:</p>
 <div class="tabbed-set docutils">
-<input checked="checked" id="44532e02-5cb0-4c85-9bd8-0aeca12c244e" name="a799f125-80b7-440e-a07b-68f38494f50d" type="radio">
-</input><label class="tabbed-label" for="44532e02-5cb0-4c85-9bd8-0aeca12c244e">
+<input checked="checked" id="d59913e9-8620-4f7b-bf07-86aee8651629" name="8211bda7-a60f-41e2-9601-f878b70770eb" type="radio">
+</input><label class="tabbed-label" for="d59913e9-8620-4f7b-bf07-86aee8651629">
 macOS</label><div class="tabbed-content docutils">
 <ol class="arabic simple">
 <li><p>Open Finder</p></li>
@@ -999,8 +999,8 @@
 <li><p><code class="docutils literal notranslate"><span class="pre">afp://duke.neuro.polymtl.ca/</span></code></p></li>
 </ol>
 </div>
-<input id="6134cfcb-d1af-48a8-8e61-e301c2b1af7f" name="a799f125-80b7-440e-a07b-68f38494f50d" type="radio">
-</input><label class="tabbed-label" for="6134cfcb-d1af-48a8-8e61-e301c2b1af7f">
+<input id="3a4766b7-8703-48b6-b040-20d8275234db" name="8211bda7-a60f-41e2-9601-f878b70770eb" type="radio">
+</input><label class="tabbed-label" for="3a4766b7-8703-48b6-b040-20d8275234db">
 Linux</label><div class="tabbed-content docutils">
 <ol class="arabic simple">
 <li><p>Open File Browser</p></li>
@@ -1008,8 +1008,8 @@
 <li><p><code class="docutils literal notranslate"><span class="pre">smb://duke.neuro.polymtl.ca/</span></code></p></li>
 </ol>
 </div>
-<input id="0cc590c1-fa8a-4362-9811-8fa916fb4a29" name="a799f125-80b7-440e-a07b-68f38494f50d" type="radio">
-</input><label class="tabbed-label" for="0cc590c1-fa8a-4362-9811-8fa916fb4a29">
+<input id="9b3abd8f-4712-4f9e-810e-6619e67322fd" name="8211bda7-a60f-41e2-9601-f878b70770eb" type="radio">
+</input><label class="tabbed-label" for="9b3abd8f-4712-4f9e-810e-6619e67322fd">
 Windows 10</label><div class="tabbed-content docutils">
 <ol class="arabic simple">
 <li><p>Open Windows explorer</p></li>
@@ -1035,8 +1035,8 @@
 <h2>Mount with Terminal<a class="headerlink" href="#mount-with-terminal" title="Permalink to this headline">#</a></h2>
 <p>You can also connect your computer from the CLI, or with a script, which might be more efficient in the long run:</p>
 <div class="tabbed-set docutils">
-<input checked="checked" id="975d6619-3cbc-457f-b7da-cc7380f0060b" name="c7c9b7d4-1402-4d88-9621-76a0cf768b07" type="radio">
-</input><label class="tabbed-label" for="975d6619-3cbc-457f-b7da-cc7380f0060b">
+<input checked="checked" id="efcf97dc-0f34-4d81-b470-f25d4215ea07" name="4ada2661-3c49-411d-b3c9-e3a2e0e02ed3" type="radio">
+</input><label class="tabbed-label" for="efcf97dc-0f34-4d81-b470-f25d4215ea07">
 Mac OSX</label><div class="tabbed-content docutils">
 <p>Create folder for the mount point on a location (your home directory) where you have read and write access:</p>
 <div class="highlight-bash notranslate"><div class="highlight"><pre><span></span>mkdir &lt;FOLDER_NAME&gt; <span class="c1"># (e.g. &lt;FOLDER_NAME&gt;=sct_testing)</span>
@@ -1047,8 +1047,8 @@
 </pre></div>
 </div>
 </div>
-<input id="9c1c1a59-5bc4-4690-ba2e-18d40bf81a44" name="c7c9b7d4-1402-4d88-9621-76a0cf768b07" type="radio">
-</input><label class="tabbed-label" for="9c1c1a59-5bc4-4690-ba2e-18d40bf81a44">
+<input id="3cb6a94d-7307-4c8c-9f6f-831d7710eb8b" name="4ada2661-3c49-411d-b3c9-e3a2e0e02ed3" type="radio">
+</input><label class="tabbed-label" for="3cb6a94d-7307-4c8c-9f6f-831d7710eb8b">
 Linux</label><div class="tabbed-content docutils">
 <p>To mount:</p>
 <div class="highlight-bash notranslate"><div class="highlight"><pre><span></span>sudo mount -t cifs //duke.neuro.polymtl.ca/&lt;FOLDER_NAME&gt; /mnt/duke/&lt;FOLDER_NAME&gt; -o <span class="nv">username</span><span class="o">=</span>&lt;GRAMES_USERNAME&gt;,noexec
diff -ru _build1/html/computing-resources/neuropoly/gpus.html _build-cleaner/html/computing-resources/neuropoly/gpus.html
--- _build1/html/computing-resources/neuropoly/gpus.html	2022-07-20 21:30:29.316177166 -0400
+++ _build-cleaner/html/computing-resources/neuropoly/gpus.html	2022-07-20 23:41:46.196545888 -0400
@@ -2154,15 +2154,15 @@
 <span id="id1"></span><h2>SSH tunnelling<a class="headerlink" href="#ssh-tunnelling" title="Permalink to this headline">#</a></h2>
 <p>If you want to run a Jupyter notebook from a remote server, or monitor a model training using tensorboard, you will need to do an SSH tunnelling to be able to pass the display from the remote cluster to your local station.</p>
 <div class="tabbed-set docutils">
-<input checked="checked" id="f9db04c0-f5dc-498c-9d73-2789aa0e45f0" name="1c9fe8f2-9fcb-4bf8-84d8-8c27c8fe5813" type="radio">
-</input><label class="tabbed-label" for="f9db04c0-f5dc-498c-9d73-2789aa0e45f0">
+<input checked="checked" id="1c0947ab-2be2-4395-8544-fd2e80694f45" name="e2330008-7d8d-4f30-afc2-d04e44161f35" type="radio">
+</input><label class="tabbed-label" for="1c0947ab-2be2-4395-8544-fd2e80694f45">
 Secure pipes</label><div class="tabbed-content docutils">
 <p>Install secure pipes and configure it as follows:
 with port_rosenber as the “Port” of the screen session and port_local is a random number (see screenshot below):</p>
 <p><img alt="" src="../../_images/tunnelling_macos.png" /></p>
 </div>
-<input id="91fad940-5064-4a07-93db-14c978bda314" name="1c9fe8f2-9fcb-4bf8-84d8-8c27c8fe5813" type="radio">
-</input><label class="tabbed-label" for="91fad940-5064-4a07-93db-14c978bda314">
+<input id="1f52a9c7-5d63-4c24-b7ca-7a5fce0691a2" name="e2330008-7d8d-4f30-afc2-d04e44161f35" type="radio">
+</input><label class="tabbed-label" for="1f52a9c7-5d63-4c24-b7ca-7a5fce0691a2">
 Terminal</label><div class="tabbed-content docutils">
 <div class="highlight-bash notranslate"><div class="highlight"><pre><span></span>ssh -N -f -L localhost:8080:localhost:PORTNUMBER username@CLUSTER.neuro.polymtl.ca
 </pre></div>
diff -ru _build1/html/computing-resources/neuropoly/index.html _build-cleaner/html/computing-resources/neuropoly/index.html
--- _build1/html/computing-resources/neuropoly/index.html	2022-07-20 21:30:28.980182278 -0400
+++ _build-cleaner/html/computing-resources/neuropoly/index.html	2022-07-20 23:41:45.876550756 -0400
@@ -1311,8 +1311,8 @@
 <h3>Home folder<a class="headerlink" href="#home-folder" title="Permalink to this headline">#</a></h3>
 <p>Every <span class="xref myst">GRAMES</span> account has a school-wide personal home folder. It is backed-up nightly.</p>
 <div class="tabbed-set docutils">
-<input checked="checked" id="67790544-2bc6-4398-a1dd-48a07a5c8668" name="8ee9e1ad-5dfe-4255-9f29-9062f652c093" type="radio">
-</input><label class="tabbed-label" for="67790544-2bc6-4398-a1dd-48a07a5c8668">
+<input checked="checked" id="2004364a-fe24-452d-bb77-0d320df17486" name="4959f135-d914-4df7-9550-d399494e197e" type="radio">
+</input><label class=" [...]

2022-07-21 03:53 UTC, kousu commented
<details>

```diff

diff -ru _build1/html/searchindex.js _build-cleaner/html/searchindex.js
--- _build1/html/searchindex.js	2022-07-20 21:30:41.239995749 -0400
+++ _build-cleaner/html/searchindex.js	2022-07-20 23:41:56.304392118 -0400
@@ -1 +1 @@
-Search.setIndex({docnames:["README","agenda-and-calendar","bibliography/README","bibliography/deep-learning","bibliography/histology","bibliography/lab-theses","bibliography/mri","bibliography/shared-paperpile-folder","bibliography/spinal-cord-injury","computer-setup","computing-resources/README","computing-resources/clusters-at-criugm","computing-resources/compute-canada","computing-resources/data/README","computing-resources/data/django","computing-resources/data/duke","computing-resources/data/git-datasets","computing-resources/neuropoly/README","computing-resources/neuropoly/cpus","computing-resources/neuropoly/gpus","computing-resources/printer","computing-resources/youtube","conferences","contact","courses","dropbox-google-drive","geek-tips/README","geek-tips/bash-shell/README","geek-tips/bash-shell/script","geek-tips/contributing","geek-tips/deep-learning/README","geek-tips/deep-learning/conditional-random-fields-crf","geek-tips/deep-learning/cuda","geek-tips/deep-learning/misc","geek-tips/deep-learning/restricted-boltzmann-machines","geek-tips/deep-learning/tensorflow","geek-tips/git","geek-tips/git-annex","geek-tips/image-processing-software/README","geek-tips/image-processing-software/advanced-normalization-tools-ants","geek-tips/image-processing-software/anima","geek-tips/image-processing-software/diffusion-simulator","geek-tips/image-processing-software/freesurfer","geek-tips/image-processing-software/fsl/README","geek-tips/image-processing-software/fsl/fsleyes","geek-tips/image-processing-software/itk-snap","geek-tips/image-processing-software/nifti","geek-tips/image-processing-software/openneuro-cli","geek-tips/image-processing-software/osirix","geek-tips/misc/README","geek-tips/misc/bitbucket","geek-tips/misc/docker/README","geek-tips/misc/docker/docker-for-deep-learning","geek-tips/misc/dropbox","geek-tips/misc/git-and-github","geek-tips/misc/jekyll","geek-tips/misc/microsoft-word","geek-tips/misc/openneuro","geek-tips/misc/sketchup","geek-tips/misc/virtual-machines/README","geek-tips/misc/virtual-machines/vagrant","geek-tips/misc/virtual-machines/virtualbox","geek-tips/misc/xquartz","geek-tips/os-guides/README","geek-tips/os-guides/linux","geek-tips/os-guides/macosx","geek-tips/programming-languages/README","geek-tips/programming-languages/c++/README","geek-tips/programming-languages/c++/installation-of-vtk-and-itk-on-mac-os-x","geek-tips/programming-languages/c++/using-xcode","geek-tips/programming-languages/matlab","geek-tips/programming-languages/python","geek-tips/useful-links","ideas-for-cool-projects","learning-and-resources/deep-learning","learning-and-resources/histology","learning-and-resources/shared-paperpile-folder","learning-and-resources/untitled","mri-scanning/README","mri-scanning/mhi-7t-agilent","mri-scanning/mni-mcgill-7t-terra","mri-scanning/unf-3t-prisma","onboarding/README","onboarding/campus-access","onboarding/computer-setup","onboarding/consultants-ra","onboarding/developer-setup","onboarding/dropbox-google-drive","onboarding/getting-started","onboarding/infrastructure","onboarding/postdoc","practical-information/README","practical-information/moving-to-montreal","practical-information/purchasing-hardware-and-lab-supplies","practical-information/purchasing-weekly-lunch","practical-information/scholarships-and-bursaries","practical-information/visa","purchasing-hardware-and-lab-supplies","rf-lab/3d-printing/README","rf-lab/3d-printing/octoprint","rf-lab/README","rf-lab/cnc-machine","rf-lab/misc","rf-lab/mri-coils-at-neuropoly","rf-lab/mri-phantoms","rf-lab/pcb-manufacturing","tips-and-tricks/README","tips-and-tricks/programming/README","tips-and-tricks/programming/c++","tips-and-tricks/programming/matlab","tips-and-tricks/programming/python","tips-and-tricks/programming/unix-shell-bash","writing-articles"],envversion:{"sphinx.domains.c":2,"sphinx.domains.changeset":1,"sphinx.domains.citation":1,"sphinx.domains.cpp":4,"sphinx.domains.index":1,"sphinx.domains.javascript":2,"sphinx.domains.math":2,"sphinx.domains.python":3,"sphinx.domains.rst":2,"sphinx.domains.std":2,sphinx:56},filenames:["README.md","agenda-and-calendar.md","bibliography/README.md","bibliography/deep-learning.md","bibliography/histology.md","bibliography/lab-theses.md","bibliography/mri.md","bibliography/shared-paperpile-folder.md","bibliography/spinal-cord-injury.md","computer-setup.md","computing-resources/README.md","computing-resources/clusters-at-criugm.md","computing-resources/compute-canada.md","computing-resources/data/README.md","computing-resources/data/django.md","computing-resources/data/duke.md","computing-resources/data/git-datasets.md","computing-resources/neuropoly/README.md","computing-resources/neuropoly/cpus.md","computing-resources/neuropoly/gpus.md","computing-resources/printer.md","computing-resources/youtube.md","conferences.md","contact.md","courses.md","dropbox-google-drive.md","geek-tips/README.md","geek-tips/bash-shell/README.md","geek-tips/bash-shell/script.md","geek-tips/contributing.md","geek-tips/deep-learning/README.md","geek-tips/deep-learning/conditional-random-fields-crf.md","geek-tips/deep-learning/cuda.md","geek-tips/deep-learning/misc.md","geek-tips/deep-learning/restricted-boltzmann-machines.md","geek-tips/deep-learning/tensorflow.md","geek-tips/git.md","geek-tips/git-annex.md","geek-tips/image-processing-software/README.md","geek-tips/image-processing-software/advanced-normalization-tools-ants.md","geek-tips/image-processing-software/anima.md","geek-tips/image-processing-software/diffusion-simulator.md","geek-tips/image-processing-software/freesurfer.md","geek-tips/image-processing-software/fsl/README.md","geek-tips/image-processing-software/fsl/fsleyes.md","geek-tips/image-processing-software/itk-snap.md","geek-tips/image-processing-software/nifti.md","geek-tips/image-processing-software/openneuro-cli.md","geek-tips/image-processing-software/osirix.md","geek-tips/misc/README.md","geek-tips/misc/bitbucket.md","geek-tips/misc/docker/README.md","geek-tips/misc/docker/docker-for-deep-learning.md","geek-tips/misc/dropbox.md","geek-tips/misc/git-and-github.md","geek-tips/misc/jekyll.md","geek-tips/misc/microsoft-word.md","geek-tips/misc/openneuro.md","geek-tips/misc/sketchup.md","geek-tips/misc/virtual-machines/README.md","geek-tips/misc/virtual-machines/vagrant.md","geek-tips/misc/virtual-machines/virtualbox.md","geek-tips/misc/xquartz.md","geek-tips/os-guides/README.md","geek-tips/os-guides/linux.md","geek-tips/os-guides/macosx.md","geek-tips/programming-languages/README.md","geek-tips/programming-languages/c++/README.md","geek-tips/programming-languages/c++/installation-of-vtk-and-itk-on-mac-os-x.md","geek-tips/programming-languages/c++/using-xcode.md","geek-tips/programming-languages/matlab.md","geek-tips/programming-languages/python.md","geek-tips/useful-links.md","ideas-for-cool-projects.md","learning-and-resources/deep-learning.md","learning-and-resources/histology.md","learning-and-resources/shared-paperpile-folder.md","learning-and-resources/untitled.md","mri-scanning/README.md","mri-scanning/mhi-7t-agilent.md","mri-scanning/mni-mcgill-7t-terra.md","mri-scanning/unf-3t-prisma.md","onboarding/README.md","onboarding/campus-access.md","onboarding/computer-setup.md","onboarding/consultants-ra.md","onboarding/developer-setup.md","onboarding/dropbox-google-drive.md","onboarding/getting-started.md","onboarding/infrastructure.md","onboarding/postdoc.md","practical-information/README.md","practical-information/moving-to-montreal.md","practical-information/purchasing-hardware-and-lab-supplies.md","practical-information/purchasing-weekly-lunch.md","practical-information/scholarships-and-bursaries.md","practical-information/visa.md","purchasing-hardware-and-lab-supplie [...]

2022-07-21 04:04 UTC, kousu requested changes
Almost there, but 

```diff
diff -ru _build1/html/rf-lab/3d-printing/index.html _build-cleaner/html/rf-lab/3d-printing/index.html
--- _build1/html/rf-lab/3d-printing/index.html	2022-07-20 21:30:39.268025751 -0400
+++ _build-cleaner/html/rf-lab/3d-printing/index.html	2022-07-20 23:41:55.180409217 -0400
@@ -1014,7 +1014,7 @@
 <p>The Modix 3D printer is remotely controlled using <a class="reference external" href="https://octoprint.org">OctoPrint</a>. To access the control interface go to the hostname and use the credentials provided above.</p>
 <ul class="simple">
 <li><p><a class="reference external" href="https://docs.google.com/document/d/1N1sCdYy1kLsIw_NDbPVM3fTg5EPaR50NNuACbf_dI6s/edit?usp=sharing">SOP Modix</a></p></li>
-<li><p><a class="reference internal" href="octoprint.html"><span class="doc">OctoPrint</span></a> configuration</p></li>
+<li><p><span class="xref std std-doc">octoprint</span> configuration</p></li>
 <li><p><a class="reference external" href="https://drive.google.com/file/d/1rtaKlBJ2HbZDDPxSDA0-g0miDM7aZjVB/view?usp=sharing">Modix adjustments</a></p></li>
 </ul>
 </section>
Only in _build1/html/rf-lab/3d-printing: octoprint.html
diff -ru _build1/html/rf-lab/3d-printing/README.html _build-cleaner/html/rf-lab/3d-printing/README.html
--- _build1/html/rf-lab/3d-printing/README.html	2022-07-20 21:30:39.268025751 -0400
+++ _build-cleaner/html/rf-lab/3d-printing/README.html	2022-07-20 23:41:55.180409217 -0400
@@ -1014,7 +1014,7 @@
 <p>The Modix 3D printer is remotely controlled using <a class="reference external" href="https://octoprint.org">OctoPrint</a>. To access the control interface go to the hostname and use the credentials provided above.</p>
 <ul class="simple">
 <li><p><a class="reference external" href="https://docs.google.com/document/d/1N1sCdYy1kLsIw_NDbPVM3fTg5EPaR50NNuACbf_dI6s/edit?usp=sharing">SOP Modix</a></p></li>
-<li><p><a class="reference internal" href="octoprint.html"><span class="doc">OctoPrint</span></a> configuration</p></li>
+<li><p><span class="xref std std-doc">octoprint</span> configuration</p></li>
 <li><p><a class="reference external" href="https://drive.google.com/file/d/1rtaKlBJ2HbZDDPxSDA0-g0miDM7aZjVB/view?usp=sharing">Modix adjustments</a></p></li>
 </ul>
 </section>
```

revealed that octoprint.md should stay. It's a real file, it should be kept.

In fact, in its case, removing the toctree warning has just added this different warning:

> /home/GRAMES.POLYMTL.CA/p115628/src/intranet.neuro.polymtl.ca/rf-lab/3d-printing/README.md:32: WARNING: unknown document: octoprint

So I think you need to put octoprint.md back and add it somewhere into the rf-lab toctree.

Otherwise, this seems to be correct. Thanks!

2022-07-25 22:42 UTC, RignonNoel commented
Good catch @kousu ! Fixed and added to rf-lab toctree just after the already existing README from the same folder.

2022-07-26 17:10 UTC, kousu commented
Okay I've rebuilt the docs a couple times and diff'd them again. This looks for now. I'm merging.

2022-07-26 17:11 UTC, kousu approved these changes

2022-07-26 17:13 UTC, merged